### ISSUE TITLE
Bug:  for hls, video will freeze when replay  in chrome.

### ISSUE THREAD

**Issue by fastfading** [videojs/http-streaming#618]
## Description
for hls, video will freeze when replay in chrome.
other browser like safari ,firefox, edge are ok.
## Sources
see attachment ,we generate it with ffmpeg.
ffmpeg -t 45 -i input.mp4  -hls_time 30 -hls_list_size 0  hls.m3u8 -y
bug not only on this  ts.   All should be the same.
for clarify the issue, we set each ts 30s,   the end ts is 15s

[Archive.zip](https://github.com/videojs/http-streaming/files/3440564/Archive.zip)

## Steps to reproduce

1.   use **chrome** to play video.js hls video (m3u8 file) until end
2.  click replay button just after video ends.

## Results
the video will freeze in the first image until the next I frame came.
### Expected
the video will not  freeze.

### Error output
no error in chrome developer tool

## Additional Information
if in step 2 we wait 15s+ , then click replay, the video will not  freeze.

### videojs-http-streaming version
latest version
videojs-http-streaming 1.10.3

### videojs version
latest version
video.js 7.6.0

### Browsers
 chrome 75

### Platforms
what platforms are affected? please include operating system and version or device and version for each
only tested in mac 10.13 and  win10

### Other Plugins
no

### Other JavaScript
to verify this, we use a pure video.js , no other js

**Comment by eschie** [comment]
I am also experiencing this issue (i believe) on chrome only with hls.  The video loads fine the first time over network, but on subsequent page refreshes, some video segments freeze while the audio continues, then picks up again.  No error output at the debug log.

**Comment by gkatsev** [comment]
Looks like the issue from the OP has been fixed in the latest version of VHS. I cannot reproduce it on https://videojs.github.io/http-streaming/, which uses VHS 1.10.6.

**Comment by eschie** [comment]
Confirmed not seeing the issue w/ VHS 1.10.6

**Comment by gkatsev** [comment]
Thanks, going to close this as fixed unless we hear otherwise. We can always re-open.

**Comment by sunzongzheng** [comment]
I tried to use the video.js@7.6.6 via cdn https://unpkg.com/video.js@7.6.6/dist/video.js. I still have the problem
